### ISSUE TITLE
distribute function's send_results_to default value is unclear

### ISSUE THREAD

**Issue by MauriceKarrenbrock** [choderalab/mpiplus#3]
Hello,

by looking at the ```distribute``` function I noticed that the default value of the ```send_results_to``` variable is unclear. In fact it is ```'all'```, the doc string says it should be ```None```, and inside the function it looks like some parts of it look for ```send_results_to``` to be ```None``` and others to be ```'all'```.

I hope I haven't misunderstood the function.

ps from the doc string I haven't really understood if ```None``` should have the same behavior of ```'all'``` or not

**Comment by andrrizzi** [comment]
Hi @MauriceKarrenbrock . If I remeber correctly, when `send_results_to` is `None` it should not send the result to any other node. This is useful if the distributed function is a routine. If this is not clear from the docstring, feel free to open a PR with a clearer message. That would be very helpful.
